name: Subtree to AEM Main Repo

on:
  workflow_dispatch:
    inputs:
      REPO:
        description: "Specify Tenant"
        required: true
jobs:
  subtree_to_aem_main:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: Swa-DevOps/CM-AEM-MAIN
          ref: refs/heads/cm/qa 

      - name: adding tenant repo
        run: |
          git remote add tonomus https://github.com/Swa-DevOps/CM-AEM-TONOMUS.git -t cm/qa
          git fetch tonomus

      - name: Subtree
        run: |
          git subtree add --prefix=tonomus https://github.com/Swa-DevOps/CM-AEM-TONOMUS.git -t  cm/qa

      - name: Push changes to AEM Main Repo
        run: |
          git push https://github.com/Swa-DevOps/CM-AEM-MAIN.git -t cm/qa
