name: Subtree to AEM Main Repo

on:
  workflow_dispatch:
    inputs:
      REPO:
        description: "Specify Tenant"
        required: true

jobs:
  subtree_to_aem_main:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Subtree split
        run: |
          # Perform subtree split to extract the relevant directory
          git subtree split --prefix=tonomus1 -b temp_branch

      - name: Clone AEM Main Repo
        run: |
          git clone -b cm/qa https://github.com/Swa-DevOps/CM-AEM-MAIN.git
          cd CM-AEM-MAIN
          git checkout cm/qa

      - name: Merge changes
        run: |
          # Merge changes from the temporary branch
          git pull ../ temp_branch

      - name: Push changes to AEM Main Repo
        run: |
          git push origin cm/qa
